### PR TITLE
Syncing changes 

### PR DESCRIPTION
**Pull request by wuoliver**
Added Features: 
Obstacle SDA download 
Map
Mission data download (cannot test because server has not been updated yet)

Updated GUI for these new features

### CODE REVIEW

**Comment by winstonliu** [comment]
Please resolve conflicts.

**Comment by wuoliver** [comment]
how?

**Comment by winstonliu** [comment]
Click on the "view command line instructions". It'll walk you through. Also [see this](https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/)

**Comment by wuoliver** [comment]
thanks

**Pull request closed without merging**
